---
- name: Check the variables
  ansible.builtin.import_playbook: variable-check.yml
  vars:
    playbook: webservers.yml

- name: Test connection and determine the remote users
  hosts: "webservers:&{{ env }}"
  gather_facts: false
  roles:
    - role: connection
      tags:
        - connection
        - always

- name: Install server stack
  hosts: "webservers:&{{ env }}"
  become: true
  roles:
    - role: common
      tags:
        - common
    - role: fail2ban
      tags:
        - fail2ban
    - role: ferm
      tags:
        - ferm
# vi:ft=yaml.ansible
