---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install essential packages
  ansible.builtin.apt:
    name: "{{ item.key }}"
    state: "{{ item.value }}"
    cache_valid_time: "{{ apt_cache_valid_time }}"
  loop: "{{ common_apt_packages | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
# vi: ft=yaml.ansible
